def a() -> Void {
	b();
}

def b() -> Void {
	c();
}

def c() -> Void {
	throw new Exception();
}
try {
	a();
} catch(Exception e) {
	e.print();
}