def a() -> Void {
	b();
}

def b() -> Void {
	c();
}

def c() -> Void {
	throw new Exception();
}

def d() -> Void {
	try {
		a();
	} catch(Exception e) {
		e.print();
	}
}
d();
printLine("Hello");